version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: tg_feed/docker/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/tg_feed/logs
#      - ./tg_feed/src:/tg_feed/src
